name: golangci-lint
on:
  push:
  pull_request:
jobs:
  pullquote:
    name: pullquote
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install pullquote
        run: ./install.sh
      - name: run pullquote
        run: ./bin/pullquote
      - name: run git diff
        run: git diff
